---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-reclaim-test
spec:
  containers:
  - name: bbox
    image: busybox
    command:
    - sleep
    - inf
    volumeMounts:
    - name: my-pvc-volume
      mountPath: /var/my-pvc-mnt
  volumes:
  - name: my-pvc-volume
    persistentVolumeClaim:
      claimName: "{{ .Values.claimName }}"
